### ISSUE TITLE
Consider resigning from Bootstrap

### ISSUE THREAD

**Issue by frontcraft** [frontcraft/bootsmacss#46]
Approach applied on Uberchord project looks promising. Bootstrap generates a lot of garbage stuff and it's best goodies can be coppied into our library. We do not need whole Bootstrap.

**Comment by bandanaman** [comment]
New bootstrap-less branch created

**Comment by frontcraft** [comment]
bootstrap-less branch moved as master branch. Version with bootstrap moved to non default branch
