### ISSUE TITLE
Wrongly links at styleguide

### ISSUE THREAD

**Issue by siberianbear** [frontcraft/bootsmacss#47]
For example open the page:
http://bandanaman.github.io/bootsmacss/styleguide/section/2.1

Try to click "full-screen" icon at any alert's samples.

You will be forwarded to 404-page like: 
http://bandanaman.github.io/bootsmacss/styleguide/section/2.1-1/fullscreen

**Comment by frontcraft** [comment]
It does not work only on GitHub pages. In localhost is fine :) I am closing it because we cannot do anything with that
