### ISSUE TITLE
New version installed on Linux, error at running gulp

### ISSUE THREAD

**Issue by siberianbear** [frontcraft/bootsmacss#49]
Here is the error message:

![issue2](https://cloud.githubusercontent.com/assets/10257160/20096807/1ae6fccc-a5de-11e6-9a39-c6761249820d.png)

**Comment by frontcraft** [comment]
We found together that it was a file permissions issue on local machine. I'm closing it for now, but maybe in the future we should consider creating the troubleshooting section.
